import { expect, test } from './fixtures.ts'

test.describe('make a mix', () => {
  test('builds a mix from a seed and saves it as a new playlist', async ({ page, orbit }) => {
    await page.locator('.library__button').click()
    await page.getByRole('button', { name: 'New mix' }).click()
    const dialog = page.getByRole('dialog', { name: 'Make a mix' })
    await expect(dialog).toBeVisible()
    await dialog.getByLabel('Make a mix from').fill('radiohead')
    await dialog.getByRole('button', { name: 'Make mix' }).click()
    const rows = dialog.locator('.mix__row')
    await expect(rows).toHaveCount(3)
    await dialog.getByRole('button', { name: 'Leave Silent Track out of the mix' }).click()
    await expect(rows).toHaveCount(2)
    await expect(dialog.locator('.mix__summary')).toContainText('Mix · radiohead · 2 songs')
    await expect(dialog.getByRole('button', { name: 'Make mix' })).toHaveClass(/button--quiet/)
    await dialog.getByRole('button', { name: 'Create playlist' }).click()
    await expect(dialog).toBeHidden()
    await expect(orbit.toast('Created “Mix · radiohead”')).toBeVisible()
    await expect(page.locator('.library__name')).toHaveText('Mix · radiohead')
    expect((await orbit.titles()).sort()).toEqual(['Clocks', 'Karma Police'])
  })

  test('explains an empty result and a failing catalog', async ({ page, orbit }) => {
    await expect(orbit.rows().first()).toBeAttached()
    await page.keyboard.press('Control+k')
    await page.locator('.palette__input').fill('make a mix')
    await page.keyboard.press('Enter')
    const dialog = page.getByRole('dialog', { name: 'Make a mix' })
    await dialog.getByLabel('Make a mix from').fill('zzzz')
    await dialog.getByRole('button', { name: 'Make mix' }).click()
    await expect(dialog.getByText('No songs found for “zzzz”')).toBeVisible()
    await dialog.getByLabel('Make a mix from').fill('fail')
    await dialog.getByRole('button', { name: 'Make mix' }).click()
    await expect(dialog.getByText('The catalog could not be reached.')).toBeVisible()
    await expect(dialog.getByRole('button', { name: 'Try again' })).toBeVisible()
    await expect(dialog.getByRole('button', { name: 'Create playlist' })).toBeHidden()
    await dialog.getByRole('button', { name: 'Cancel' }).click()
    await expect(dialog).toBeHidden()
  })
})
