import { expect, test } from './fixtures.ts'

const volume = (page: import('@playwright/test').Page) => page.evaluate(() => window.orbitFakePlayer?.volume ?? -1)
const playing = (page: import('@playwright/test').Page) => page.evaluate(() => window.orbitFakePlayer?.playing ?? false)

test.describe('smooth volume transitions', () => {
  test('fades out before pausing and back in when resuming', async ({ page, orbit }) => {
    await page.clock.install()
    await page.reload()
    await expect(orbit.rows().first()).toBeAttached()
    await orbit.play()
    await page.clock.runFor(1000)
    expect(await volume(page)).toBe(80)
    await page.locator('.play').click()
    await page.clock.runFor(150)
    const middle = await volume(page)
    expect(middle).toBeGreaterThan(0)
    expect(middle).toBeLessThan(80)
    expect(await playing(page)).toBe(true)
    await page.clock.runFor(400)
    expect(await playing(page)).toBe(false)
    expect(await volume(page)).toBe(80)
    await page.locator('.play').click()
    await page.clock.runFor(100)
    expect(await volume(page)).toBeLessThan(80)
    await page.clock.runFor(600)
    expect(await volume(page)).toBe(80)
  })

  test('can be turned off so pausing is immediate', async ({ page, orbit }) => {
    await orbit.openMenu('Settings')
    await expect(page.getByRole('switch', { name: /Smooth volume transitions/ })).toBeChecked()
    await page.locator('label[for="setting-smooth"]').click()
    await page.keyboard.press('Escape')
    await page.clock.install()
    await page.reload()
    await expect(orbit.rows().first()).toBeAttached()
    await orbit.play()
    await page.clock.runFor(500)
    await page.locator('.play').click()
    await page.clock.runFor(20)
    expect(await playing(page)).toBe(false)
    expect(await volume(page)).toBe(80)
  })
})
